# -*- coding: utf-8 -*-
"""part3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1N1TSjd381W4Gp-QcV9slaXFdifjhwvD4
"""

from datetime import date,timedelta
import numpy as np
import pandas as pd
from pandas import datetime

jio = pd.read_csv('jio.csv', parse_dates=['Date'])
NIFTY = pd.read_csv('NIFTY.csv', parse_dates=['Date'])
airtel = pd.read_csv('airtel.csv', parse_dates=['Date'])
stocks = [jio, airtel, NIFTY]
jio.name = 'jio'
NIFTY.name = 'NIFTY'
airtel.name = 'airtel'

NIFTY.head()

NIFTY.drop(columns = ["Date"],inplace=True)

NIFTY

Open = NIFTY["Open"]
High = NIFTY["High"]
Low = NIFTY["Low"]
Close = NIFTY["Close"]

X = NIFTY.drop(columns=["Open","High","Low","Close"])

X.info()

from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test = train_test_split(X,Close,test_size = .2,random_state = 2)

sc.fit(x_train)

x_train = sc.transform(x_train)
x_test = sc.transform(x_test)

x_train.shape,x_test.shape

from sklearn.linear_model import LinearRegression

from sklearn.model_selection import GridSearchCV
from sklearn.metrics import confusion_matrix
from sklearn.svm import SVR

parameters = {'kernel': ('rbf','poly'), 'C':[1, 10],'gamma': [.1, .3],'epsilon':[0.1,0.3]}

svr = SVR()
grid_search = GridSearchCV(estimator=svr,param_grid = parameters,scoring = 'accuracy', cv = 5, n_jobs = -1)

grid_search = grid_search.fit(x_train,y_train)

